/*
 * @Author: lhajh
 * @File: 常量文件
 * @Date: 2018-04-13 16:53:58
 * @Last Modified by: lhajh
 * @Last Modified time: 2018-04-24 19:49:43
 */

// 主题文件数组
const themeArray = [
  'index',
  // 'alert',
  // 'autocomplete',
  // 'badge',
  // 'base',
  // 'breadcrumb-item',
  // 'breadcrumb',
  // 'button-group',
  // 'button',
  // 'card',
  // 'carousel-item',
  // 'carousel',
  // 'cascader',
  // 'checkbox-button',
  // 'checkbox-group',
  // 'checkbox',
  // 'col',
  // 'collapse-item',
  // 'collapse',
  // 'color-picker',
  // 'date-picker',
  // 'dialog',
  // 'dropdown-item',
  // 'dropdown-menu',
  // 'dropdown',
  // 'form-item',
  // 'form',
  // 'icon',
  // 'input-number',
  // 'input',
  // 'loading',
  // 'menu-item-group',
  // 'menu-item',
  // 'menu',
  // 'message-box',
  // 'message',
  // 'notification',
  // 'option-group',
  // 'option',
  // 'pagination',
  // 'popover',
  // 'progress',
  // 'radio-button',
  // 'radio-group',
  // 'radio',
  // 'rate',
  // 'row',
  // 'scrollbar',
  // 'select-dropdown',
  // 'select',
  // 'slider',
  // 'spinner',
  // 'step',
  // 'steps',
  // 'submenu',
  // 'switch',
  // 'tab-pane',
  // 'table-column',
  // 'table',
  // 'tabs',
  // 'tag',
  // 'time-picker',
  // 'time-select',
  // 'tooltip',
  // 'transfer',
  // 'tree',
  // 'upload',
  'custom'
]

export default themeArray
